## Pair Programming Pandas II

### Lección 2 - Pandas II: Carga y guardado de datos

#### Judith Mellidez y Sonia Ruiz

En este ejercicio de pair programming pondremos en práctica como cargar distintos tipos de archivos en Python usando Pandas.
     Al final de la explicación encontrareís una serie de ficheros con distintos formatos.
Los objetivos de este pair programming:

In [1]:
#Importamos las librerias:
import pandas as pd 
import numpy as np 
import pickle 
import os
from locale import getpreferredencoding

- Id cargando todos los ficheros en vuestro jupyter.

  - Si os da error leer el pickle será por la versión de pandas. Podéis guardar el csv como pickle y cargarlo de ahí.

In [3]:
#Obtenemos la ruta donde se ubica el jupyter en el que nos encontramos.
os.getcwd()

'/Users/ju/Documents/Adalab/DA-promoc-modulo2-sprint1-judithysonia/pandas'

In [4]:
#Lectura fichero quejas.csv, añadiendo sep= ';' y especificado su encoding= 'lantin_1'

df_quejas_csv=pd.read_csv('/Users/ju/Documents/Adalab/DA-promoc-modulo2-sprint1-judithysonia/pandas/quejas.csv', sep= ';', encoding='latin_1')

,tipo,estado,canal_entrada,fecha_entrada,fecha_contestacion,consejeria,unidad_descripcion,tema,subtema
0,Queja,Recepcionada por Unidad,INTERNET,2022-01-28 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
1,Queja,Recepcionada por Unidad,INTERNET,2022-03-28 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
2,Queja,Recepcionada por Unidad,INTERNET,2022-03-23 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
3,Queja,Recepcionada por Unidad,INTERNET,2022-01-24 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
4,Queja,Recepcionada por Unidad,INTERNET,2022-03-29 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",D.G. de Descarbonización y Transición Energética,ENERGÍA,NaN
...,...,...,...,...,...,...,...,...,...
4494,Sugerencia,Cancelada,INTERNET,2022-01-02 00:00:00,NaN,"Consejería de Medio Ambiente, Vivienda y Agric...",NaN,OTROS,OTROS
4495,Sugerencia,Rechazada por SGAC,INTERNET,2022-03-08 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4496,Queja,Rechazada por SGAC,INTERNET,2022-01-24 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4497,Queja,Rechazada por SGAC,INTERNET,2022-01-21 00:00:00,NaN,NaN,NaN,OTROS,Sin valor
4498,Queja,Rechazada por SGAC,INTERNET,2022-01-21 00:00:00,NaN,NaN,NaN,OTROS,Sin valor

In [24]:
#Lectura fichero quejas.json. 

df_quejas_json=pd.read_json('/Users/ju/Documents/Adalab/DA-promoc-modulo2-sprint1-judithysonia/pandas/quejas.json')

In [27]:
#Dataframe del fichero original quejas.json
df_quejas_json

                                                   data
0     {'unidad_descripcion': 'D.G. de Descarbonizaci...
1     {'unidad_descripcion': 'D.G. de Descarbonizaci...
2     {'unidad_descripcion': 'D.G. de Descarbonizaci...
3     {'unidad_descripcion': 'D.G. de Descarbonizaci...
4     {'unidad_descripcion': 'D.G. de Descarbonizaci...
...                                                 ...
4442  {'unidad_descripcion': '', 'tipo': 'Sugerencia...
4443  {'unidad_descripcion': '', 'tipo': 'Sugerencia...
4444  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...
4445  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...
4446  {'unidad_descripcion': '', 'tipo': 'Queja', 'e...

[4447 rows x 1 columns]

In [25]:
#A continuacion utilizamos el metodo necesario para la correcta lectura del fichero
df_quejas_json2=df_quejas_json['data'].apply(pd.Series)

In [26]:
#Fichero una vez aplicamos el metodo para su correcta lectura
df_quejas_json2

,unidad_descripcion,tipo,estado,tema,consejeria,fecha_contestacion,canal_entrada,fecha_entrada,subtema
0,D.G. de Descarbonización y Transición Energética,Queja,Recepcionada por Unidad,ENERGÍA,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-01-28 00:00:00,N/A
1,D.G. de Descarbonización y Transición Energética,Queja,Recepcionada por Unidad,ENERGÍA,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-03-28 00:00:00,N/A
2,D.G. de Descarbonización y Transición Energética,Queja,Recepcionada por Unidad,ENERGÍA,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-03-23 00:00:00,N/A
3,D.G. de Descarbonización y Transición Energética,Queja,Recepcionada por Unidad,ENERGÍA,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-01-24 00:00:00,N/A
4,D.G. de Descarbonización y Transición Energética,Queja,Recepcionada por Unidad,ENERGÍA,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-03-29 00:00:00,N/A
...,...,...,...,...,...,...,...,...,...
4442,,Sugerencia,Cancelada,OTROS,"Consejería de Medio Ambiente, Vivienda y Agric...",,INTERNET,2022-01-02 00:00:00,OTROS
4443,,Sugerencia,Rechazada por SGAC,OTROS,,,INTERNET,2022-03-08 00:00:00,Sin valor
4444,,Queja,Rechazada por SGAC,OTROS,,,INTERNET,2022-01-24 00:00:00,Sin valor
4445,,Queja,Rechazada por SGAC,OTROS,,,INTERNET,2022-01-21 00:00:00,Sin valor
4446,,Queja,Rechazada por SGAC,OTROS,,,INTERNET,2022-01-21 00:00:00,Sin valor

In [6]:
#Lectura fichero quejas.xlsx. 

df_quejas_xlsx=pd.read_excel('/Users/ju/Documents/Adalab/DA-promoc-modulo2-sprint1-judithysonia/pandas/quejas.xlsx')

          DESCRIPCION_TEMA                                DESCRIPCION_SUBTEMA
0    ATENCIÓN AL CIUDADANO                         ADMINISTRACIÓN ELECTRÓNICA
1    ATENCIÓN AL CIUDADANO                                    FUNCIÓN PÚBLICA
2    ATENCIÓN AL CIUDADANO  OFICINAS DE ATENCIÓN AL CIUDADANO DE LA COMUNI...
3    ATENCIÓN AL CIUDADANO     OFICINAS DE REGISTRO DE LA COMUNIDAD DE MADRID
4    ATENCIÓN AL CIUDADANO                                              OTROS
..                     ...                                                ...
179               VIVIENDA                                       PLAN ALQUILA
180               VIVIENDA                             PLAN DE VIVIENDA JOVEN
181               VIVIENDA                                 PORTAL DE VIVIENDA
182               VIVIENDA                   PUNTOS DE INFORMACIÓN Y REGISTRO
183               VIVIENDA                                VIVIENDAS DEL IVIMA

[184 rows x 2 columns]

In [7]:
#Lectura fichero algas.pikle, 

df_quejas_pickle=pd.read_pickle('/Users/ju/Documents/Adalab/DA-promoc-modulo2-sprint1-judithysonia/pandas/algas.pikle')

,Unnamed: 0,lon,lat,locality,year,month,kingdom,class,family,genus,species,new,state,country,fecha,day,number_ind
0,22,-70.7167,43.0750,New Castle,1900,5.0,Chromista,Phaeophyceae,Fucaceae,Fucus,Fucus vesiculosus,"43.075,-70.7167",New Hampshire,United States,1900-05-01,1,4
1,23,-70.7167,43.0750,New Castle,1900,5.0,Chromista,Phaeophyceae,Fucaceae,Fucus,Fucus vesiculosus,"43.075,-70.7167",New Hampshire,United States,1900-05-01,1,3
2,24,-70.7167,43.0750,New Castle,1900,5.0,Plantae,Florideophyceae,Palmariaceae,Palmaria,Palmaria palmata,"43.075,-70.7167",New Hampshire,United States,1900-05-01,1,9
3,33,-158.1170,21.5833,Haleiwa,1900,6.0,Plantae,Ulvophyceae,Ulvaceae,Ulva,Ulva lactuca,"21.5833,-158.117",Hawaii,United States,1900-06-01,1,7
4,35,-7.0000,62.1800,Hvalvík,1900,6.0,Chromista,Phaeophyceae,Alariaceae,Alaria,Alaria esculenta,"62.18,-7.0",Streymoyar sýsla,Føroyar,1900-06-01,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6691,27748,-125.1548,48.8266,Bamfield,2020,2.0,Chromista,Phaeophyceae,Sargassaceae,Sargassum,Sargassum muticum,"48.8266,-125.1548",British Columbia,Canada,2020-02-01,1,10
6692,27752,-125.1549,48.8264,Bamfield,2020,2.0,Chromista,Phaeophyceae,Sargassaceae,Sargassum,Sargassum muticum,"48.8264,-125.1549",British Columbia,Canada,2020-02-01,1,3
6693,27759,-125.1550,48.8264,Bamfield,2020,2.0,Plantae,Ulvophyceae,Ulvaceae,Ulva,Ulva lactuca,"48.8264,-125.155",British Columbia,Canada,2020-02-01,1,5
6694,27776,-125.1549,48.8264,Bamfield,2020,2.0,Chromista,Phaeophyceae,Sargassaceae,Sargassum,Sargassum muticum,"48.8264,-125.1549",British Columbia,Canada,2020-02-01,1,10
6695,27781,-125.1542,48.8269,Bamfield,2020,2.0,Plantae,Ulvophyceae,Ulvaceae,Ulva,Ulva lactuca,"48.8269,-125.1542",British Columbia,Canada,2020-02-01,1,6

## Ejercicio 2

- Para poner el práctica el read_clipboard elegir alguna tabla que os podaís encontrar en google y usad dicho método 
para traer los datos al jupyter notebook. Una vez que los hayáis cargado, guardad esos datos en los siguientes formatos:
   - csv
   - excel
   - json
   - pickle

In [9]:
# Hemos extraido los valores de la tabla de partes de nieve del buscador "Info nieve" utilizando el metodo "pd.read_clipboard()".
# Para su lectura hemos creado un DataFrame

df_nieve= pd.read_clipboard()
df_nieve

              Estación Estado Remontes     Pistas Kilómetros      Nieve  Meteo
0                 100K  Astún        -  Candanchú       None       None    NaN
1                Parte    del  Viernes          2         de  Diciembre    NaN
2              Cerrada   -/38    -/112    -/100,5       None       None    NaN
3                   KM      -       CM          -       None       None    NaN
4                Astún   None     None       None       None       None    NaN
5                Parte    del  Viernes          2         de  Diciembre    NaN
6              Cerrada   -/15     -/61       -/50       None       None    NaN
7                   KM      -       CM       None       None       None    NaN
8               -8º/0º   None     None       None       None       None    NaN
9            Candanchú   None     None       None       None       None    NaN
10               Parte    del  Viernes          2         de  Diciembre    NaN
11             Cerrada   -/23     -/51     -/50,5       None       None    NaN
12                  KM      -       CM       None       None       None    NaN
13              -7º/1º   None     None       None       None       None    NaN
14              Cerler   None     None       None       None       None    NaN
15               Parte    del  Viernes          2         de  Diciembre    NaN
16             Cerrada   -/20     -/72       -/80       None       None    NaN
17                  KM      -       CM       None       None       None    NaN
18              -9º/1º   None     None       None       None       None    NaN
19  Formigal-Panticosa   None     None       None       None       None    NaN
20               Parte    del  Viernes          2         de  Diciembre    NaN
21             Cerrada   -/37    -/147      -/182       None       None    NaN
22                  KM      -       CM          -       None       None    NaN
23            Formigal   None     None       None       None       None    NaN
24               Parte    del  Viernes          2         de  Diciembre    NaN
25             Cerrada   -/22    -/102      -/143       None       None    NaN
26                  KM      -       CM       None       None       None    NaN
27              -7º/0º   None     None       None       None       None    NaN
28           Panticosa   None     None       None       None       None    NaN
29               Parte    del  Viernes          2         de  Diciembre    NaN
30             Cerrada   -/15     -/45       -/39       None       None    NaN
31                  KM   None     None       None       None       None    NaN

    - Guardamos el dataframe en las siguientes extensiones:

In [13]:
df_nieve.to_csv('pista_ski_aragon.csv')

In [14]:
df_nieve.to_excel('pista_ski_aragon.xlsx')

In [15]:
df_nieve.to_json('pista_ski_aragon.json')

In [16]:
df_nieve.to_pickle('pista_ski_aragon.pickle')

In [22]:
# AUTO BONUS
# Limpieza de filas del fichero df_nieve
df_nieve_limpio=df_nieve.drop([1,5,10,15,20,24,29])
df_nieve_limpio

              Estación Estado Remontes     Pistas Kilómetros Nieve  Meteo
0                 100K  Astún        -  Candanchú       None  None    NaN
2              Cerrada   -/38    -/112    -/100,5       None  None    NaN
3                   KM      -       CM          -       None  None    NaN
4                Astún   None     None       None       None  None    NaN
6              Cerrada   -/15     -/61       -/50       None  None    NaN
7                   KM      -       CM       None       None  None    NaN
8               -8º/0º   None     None       None       None  None    NaN
9            Candanchú   None     None       None       None  None    NaN
11             Cerrada   -/23     -/51     -/50,5       None  None    NaN
12                  KM      -       CM       None       None  None    NaN
13              -7º/1º   None     None       None       None  None    NaN
14              Cerler   None     None       None       None  None    NaN
16             Cerrada   -/20     -/72       -/80       None  None    NaN
17                  KM      -       CM       None       None  None    NaN
18              -9º/1º   None     None       None       None  None    NaN
19  Formigal-Panticosa   None     None       None       None  None    NaN
21             Cerrada   -/37    -/147      -/182       None  None    NaN
22                  KM      -       CM          -       None  None    NaN
23            Formigal   None     None       None       None  None    NaN
25             Cerrada   -/22    -/102      -/143       None  None    NaN
26                  KM      -       CM       None       None  None    NaN
27              -7º/0º   None     None       None       None  None    NaN
28           Panticosa   None     None       None       None  None    NaN
30             Cerrada   -/15     -/45       -/39       None  None    NaN
31                  KM   None     None       None       None  None    NaN

Happy coding 💪🏽