# Ejercicios Pair Programming - Modulo 2 - Sprint 1 
## Lección 4 - Pandas IV: Filtrado de datos
### Judith Mellidez y Sonia Ruiz

Hoy seguiremos trabajando con el csv de ataques que exploramos ayer. Para eso, ayer guardasteis al final del pair programming al que le habíamos elimiando algunas columnas. 
Utilizad ese fichero. En la lección de hoy tendréis que ir contestando una serie de preguntas que os planteamos. Para ello tendréis que aplicar los conocimientos 
adquiridos en la clase invertida sobre como filtrar datos en el DataFrame y como reemplazar valores en el DataFrame.

1. Cargad el csv que guardasteis ayer.
Antes de seguir con las preguntas, este DataFrame está terriblemente sucio. En las próximas sesiones lo iremos limpiando. Para evitar posibles errores con los nulos vamos a eliminar todos los nulos del DataFrame. Para ello vamos a utilizar el método .dropna() de pandas. Tendréis que ejecutar la siguiente línea de código para eliminar los nulos del DataFrame y poder seguir haciendo el resto de los ejercicios.

- ¿Cuántas filas se han eliminado con esta línea de código?
df.dropna(inplace = True)

In [20]:
#Importamos las librerias:
import pandas as pd
import numpy as np

In [31]:
#Creamos el dataframe a partir del archivo .csv .
attacks_lec3=pd.read_csv('data_pandas_lec3/attacks_lec3.csv')
attacks_lec3.head()

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2018.06.18,1,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2018.06.09,2,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2018.06.08,3,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2018.06.04,4,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...

In [33]:
#Con el metodo shape exploramos las filas y columnas que tenemos en el DataFrame
shape1=attacks_lec3.shape
shape1

(6114, 14)

In [22]:
#Con el metodo info() exploramos nombre y numero de columnas, numero de valores not null y tipo de datos que tenemos en el DataFrame
attacks_lec3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6114 entries, 0 to 6113
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   case_number  6113 non-null   object
 1   unnamed:_0   6114 non-null   int64
 2   year         6114 non-null   float64
 3   type         6110 non-null   object
 4   country      6074 non-null   object
 5   area         5706 non-null   object
 6   location     5626 non-null   object
 7   activity     5603 non-null   object
 8   name         5914 non-null   object
 9   sex_         5564 non-null   object
 10  age          3448 non-null   object
 11  time         2934 non-null   object
 12  species_     3409 non-null   object
 13  href         6114 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 668.8+ KB

In [23]:
#Resumen de datos estadisticos numericos
attacks_lec3.describe()

        unnamed:_0         year
count  6114.000000  6114.000000
mean   3065.554629  1968.831207
std    1769.652139    43.745920
min       0.000000  1801.000000
25%    1534.250000  1946.000000
50%    3066.500000  1980.000000
75%    4596.750000  2005.000000
max    6131.000000  2018.000000

In [24]:
#Nos devuelve la cantidad de valores que son nulos en cada columna.
attacks_lec3.isnull().sum()

case_number       1
unnamed:_0        0
year              0
type              4
country          40
area            408
location        488
activity        511
name            200
sex_            550
age            2666
time           3180
species_       2705
href              0
dtype: int64

In [34]:
#Eliminamos las filas con valores nulos. Consideramos que no son buenas practicas eliminar los nulos sin observar
#  detenidamente el dataframe.
attacks_lec3.dropna(inplace=True)
attacks_lec3

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
13,2018.05.13.a,13,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5905,1868.05.13,5922,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...

In [35]:
#Obtenemos las forma del dataframe donde el primer elemento son las filas y el segundo las columnas.
shape2=attacks_lec3.shape
shape2

(1502, 14)

In [26]:
#Comprobamos que hemos eliminado los valores nulos.
attacks_lec3.isnull().sum()

case_number    0
unnamed:_0     0
year           0
type           0
country        0
area           0
location       0
activity       0
name           0
sex_           0
age            0
time           0
species_       0
href           0
dtype: int64

In [30]:
attacks_lec3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1502 entries, 0 to 5905
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   case_number  1502 non-null   object
 1   unnamed:_0   1502 non-null   int64
 2   year         1502 non-null   float64
 3   type         1502 non-null   object
 4   country      1502 non-null   object
 5   area         1502 non-null   object
 6   location     1502 non-null   object
 7   activity     1502 non-null   object
 8   name         1502 non-null   object
 9   sex_         1502 non-null   object
 10  age          1502 non-null   object
 11  time         1502 non-null   object
 12  species_     1502 non-null   object
 13  href         1502 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 176.0+ KB

In [38]:
filas_eliminadas= shape1[0] - shape2[0]
print('Numero de filas eliminadas son:', filas_eliminadas)

Numero de filas eliminadas son: 4612

2. ¿Cuál es el número de ataques que se han producido en Estados Unidos?

In [53]:
#Mostramos los valores unicos de la columna paises y se puede observar que estan en ingles y en mayusculas.
countries=attacks_lec3['country'].unique()
coutries1=np.sort(countries)
coutries1

array(['AMERICAN SAMOA', 'ARGENTINA', 'AUSTRALIA', 'BAHAMAS', 'BERMUDA',
       'BRAZIL', 'BRITISH WEST INDIES', 'COLUMBIA', 'COSTA RICA',
       'CROATIA', 'CUBA', 'ECUADOR', 'EGYPT', 'EL SALVADOR', 'ENGLAND',
       'FEDERATED STATES OF MICRONESIA', 'FIJI', 'FRENCH POLYNESIA',
       'GRAND CAYMAN', 'GREECE', 'GUAM', 'HONG KONG', 'INDIA',
       'INDONESIA', 'IRAQ', 'ISRAEL', 'ITALY', 'JAMAICA', 'JAPAN',
       'MALDIVES', 'MARSHALL ISLANDS', 'MAURITIUS', 'MEXICO',
       'MICRONESIA', 'MOZAMBIQUE', 'NEW BRITAIN', 'NEW CALEDONIA',
       'NEW ZEALAND', 'NORTH PACIFIC OCEAN', 'OKINAWA', 'PACIFIC OCEAN',
       'PALAU', 'PANAMA', 'PAPUA NEW GUINEA', 'PHILIPPINES', 'REUNION',
       'RUSSIA', 'SCOTLAND', 'SENEGAL', 'SEYCHELLES', 'SOLOMON ISLANDS',
       'SOUTH AFRICA', 'SOUTH KOREA', 'SPAIN', 'ST. MAARTIN', 'TAIWAN',
       'THAILAND', 'TONGA', 'TURKS & CAICOS', 'UNITED KINGDOM', 'USA',
       'VANUATU', 'VENEZUELA', 'VIETNAM'], dtype=object)

In [48]:
#Mostramos solos datos del dataframe con los ataques en el pais "USA".
attacks_USA=attacks_lec3[attacks_lec3['country']== 'USA']
attacks_USA

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
35,2018.03.31,35,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
53,2017.12.31,53,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
60,2017.11.24,60,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4731,1941.06.15,4743,1941.0,Provoked,USA,New York,15 miles south of Jones Inlet,Fishing from 32' boat,Paul Ruhle,M,43,14h00,2.1 m [7'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4734,1941.03.09,4746,1941.0,Provoked,USA,California,"Santa Monica, Los Angeles County",Fishing,Frank Martinez,M,53,Night,Mako shark (aka bonito shark) 1.2 m [4'],http://sharkattackfile.net/spreadsheets/pdf_di...
4862,1936.07.25,4874,1936.0,Unprovoked,USA,Massachusetts,"Hollywood Beach, just above Mattapoisett Harbo...",Swimming crawl stroke,"Joseph Troy, Jr",M,16,15h30,White shark (identified by Dr. Hugh Smith),http://sharkattackfile.net/spreadsheets/pdf_di...
5136,1926.07.08,5148,1926.0,Unprovoked,USA,California,"San Francisco Bay (or San Leandro Bay), near c...",Swimming with dog near canning factory,Norman Piexotto,M,15,,1.5 m [5'] white shark or sevengill shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5297,1916.07.01,5311,1916.0,Unprovoked,USA,New Jersey,"Beach Haven, Ocean County",Swimming,Charles E. Vansant,M,24,17h00,Thought to involve a 2.6 m [8.5'] white shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [50]:
shape3= attacks_USA.shape
print('El numero de ataques en Estados Unidos ha sido:', shape3[0])

El numero de ataques en Estados Unidos ha sido: 719

3. ¿Y en España?

- 3.1 ¿En qué regiones se han producido los ataques (columna location) ?

In [55]:
#Mostramos solos datos del dataframe con los ataques en el pais "SPAIN".
attacks_SPAIN=attacks_lec3[attacks_lec3['country']== 'SPAIN']
attacks_SPAIN

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
98,2017.08.26.b,98,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...
233,2016.07.29,234,2016.0,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,11h30,Blue shark,http://sharkattackfile.net/spreadsheets/pdf_di...
377,2015.08.18.a,378,2015.0,Invalid,SPAIN,Alicante,"Poniente Beach, Benidorm",Swimming,male,M,10,11h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
1007,2010.07.16.b,1011,2010.0,Provoked,SPAIN,Grand Canary Island,"Sardina del Norte, Gáldar",Swimming,male,M,9,19h15,Angel shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2469,1993.09.03,2476,1993.0,Unprovoked,SPAIN,Costa Blanca,"Playa de las Arenas, Valencia",Swimming,Jorge Durich Heredia (or Hernandez),M,69,08h00,1.2 m [4'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [56]:
shape4= attacks_SPAIN.shape
print('El numero de ataques en España ha sido:', shape4 [0])

El numero de ataques en España ha sido: 5

In [61]:
attacks_loc_SPAIN=attacks_SPAIN['location'].unique()
print('Las regiones donde se han producido los ataques en España son:', attacks_loc_SPAIN)

Las regiones donde se han producido los atques en España son: ['Grao de Moncofa' 'Arenales del Sol' 'Poniente Beach, Benidorm'
 'Sardina del Norte, Gáldar' 'Playa de las Arenas, Valencia ']

 - 3.2 ¿Cuántos ataques se han producido en cada área (columna area?

In [63]:
#aplicamos el metodo '.value_counts()' para extraer la informacion especifica del numero de ataques sufridos por area.
attacks_area_SPAIN=attacks_SPAIN['area'].value_counts()
attacks_area_SPAIN

Castellón              1
Alicante Province      1
Alicante               1
Grand Canary Island    1
Costa Blanca           1
Name: area, dtype: int64

4. Extraed un DataFrame nuevo con los ataques que se han producido en Australia y Estados Unidos. 
📌 Nota Este ejercicio se puede resolver usando dos condiciones de filtrado o usando el método isin(). 
Hacedlo con ambas herramientas.

In [66]:
#Un metodo para crear el DataFrame solicitado seria:
attacks_USA_AUSTRALIA=attacks_lec3[(attacks_lec3['country']== 'USA') | (attacks_lec3['country'] == 'AUSTRALIA')] 
attacks_USA_AUSTRALIA

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
21,2018.04.25.a,21,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
35,2018.03.31,35,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5359,1912.01.26,5375,1912.0,Unprovoked,AUSTRALIA,New South Wales,"Fig Tree Bridge, Lane Cove River, near Sydney",Swimming,James Edward Morgan,M,21,15h00,"2.8 m [9'3""] whaler shark captured 3 days late...",http://sharkattackfile.net/spreadsheets/pdf_di...
5481,1905.03.26,5498,1905.0,Unprovoked,AUSTRALIA,New South Wales,Lismore,Bathing,Richard Owen,M,40,Morning,5' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [67]:
#Otro metodo que podemos utilizar para crear el DataFrame es '.isin()'.
attacks_USA_AUSTRALIA_isn=attacks_lec3[attacks_lec3['country'].isin(['USA','AUSTRALIA'])]
attacks_USA_AUSTRALIA_isn

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
21,2018.04.25.a,21,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
35,2018.03.31,35,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5359,1912.01.26,5375,1912.0,Unprovoked,AUSTRALIA,New South Wales,"Fig Tree Bridge, Lane Cove River, near Sydney",Swimming,James Edward Morgan,M,21,15h00,"2.8 m [9'3""] whaler shark captured 3 days late...",http://sharkattackfile.net/spreadsheets/pdf_di...
5481,1905.03.26,5498,1905.0,Unprovoked,AUSTRALIA,New South Wales,Lismore,Bathing,Richard Owen,M,40,Morning,5' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...

- 4.1 ¿Cuántos ataques se han producido en cada país?

In [68]:
#Empleando el metodo ".value_counts()" obtenemos el recuento de filas para cada valor unico de la columna especificada.
attacks_cases_USA_AUSTRALIA=attacks_USA_AUSTRALIA['country'].value_counts()
attacks_cases_USA_AUSTRALIA

USA          719
AUSTRALIA    324
Name: country, dtype: int64

- 4.2 ¿Ha habido ataques en Australia a gente que estuviera remando (lo encontrareis como Paddling en el DataFrame en la columna activity)?

In [73]:
#Comprobamos todas las actividades registradas en el momento del ataque.
attasck_act_USA_AUS=attacks_USA_AUSTRALIA['activity'].unique()
attasck_act_USA_AUS

array(['Paddling', 'Walking', 'Feeding sharks', 'Surfing',
       'Stand-Up Paddleboarding', 'Wading', 'Swimming', 'Spearfishing',
       'Kayaking / Fishing', 'Snorkeling', 'SUP', 'Fishing', 'Kayaking',
       'Body boarding', 'Scuba Diving', 'Surf fishing', 'Floating',
       'SUP Foil boarding', 'Kite surfing', 'Floating in tube',
       'Standing', 'Diving', 'Teasing a shark', 'Paddle boarding',
       'Kayak Fishing', 'Surf-skiing', 'Scallop diving on hookah',
       'Body boarding ', 'Playing in the water', 'Boogie boarding',
       'Playing', 'Surf skiing ', 'Standing / Snorkeling', 'Rowing',
       'Shark fishing', 'Fishing ', 'Kayaking ', 'Body surfing',
       'Diving for lobsters', 'Kiteboarding', 'Diving ',
       'Diving for Abalone', 'Casting a net', 'Boogie Boarding',
       'Playing in the surf', 'Bodyboarding',
       'Swimming or boogie boarding', 'Free diving ',
       'Sitting in the water', 'Scuba diving', 'Diving, feeding sharks',
       'Kite Surfing', 'Washing sand off a speared fish', 'Surfing ',
       'Wakeboarding', 'Diving for abalone', 'Measuring sharks',
       'Wade Fishing', 'Crawling',
       'Diving, but on the surface when bitten by the shark',
       'Treading water', 'Walking out of the water after surfing',
       'Jet skiing',
       "Accidentally stood on hooked shark's tail before attempting to gut it ",
       'Jumping', 'Floating near boat & observing bioluminesce',
       'Jumped into the water', 'Reviving a sedated shark',
       'Swimming / jumping off a jetty', 'Playing soccer in the water',
       'Free diving', 'Boogie boarding, kicked at object in the water',
       'Holding onto an inflatable boat', 'Swimming with boogie board',
       'Diving in aquarium display tank',
       'Scurfing (surfboard being  towed behind a boat)',
       'Wading / fishing & carrying a bag of fish', 'Tandem surfing',
       'Free diving & spearfishing', 'Wading near a fishing net',
       'Standing, stepped on shark',
       'Swimming, wearing black wetsuit & swim fins',
       'Walking, carrying surfboard & stepped on shark',
       'Swimming with pod of dolphins', 'Swimming (using a float)',
       'Fishing from Surfboard', 'Boogie boarding or Surfing',
       'Wading, when he stepped on the shark', 'Shark Fishing',
       'Floating on a raft', 'Fishing, removing the shark from his line',
       'Scallop diving (using surface-supplied air & a POD) ',
       'Surfing, but standing in water alongside board',
       'Swimming / Wading', 'Body-boarding',
       'Swimming /  boogie boarding',
       'Surfing, fell off surfboard & stepped on the shark.',
       'Wreck / Technical diving', 'Swimming ',
       'Standing alongside surfboard', 'Swimming / snorkeling',
       'Swimming / Body surfing', 'Windsurfing, but sitting on his board',
       'Surfing / Wading',
       'Spearfishing, holding mesh bag with speared fish',
       'Surfing, lying on surfboard', "Lying prone in 2' of water",
       'Swimming with dolphins', 'Wading in school of baitfish',
       'Splashing / wading', 'Windsurfing', 'Swimming near pod of whales',
       'Free diving for abalone', 'Surfing (lying prone on his board)',
       'Swimming or paddle boarding',
       'Scuba diving (submerged riding a scooter)',
       'Body boarding or surfing', 'Surfing (sitting on his board)',
       'Wading / Surfing', 'Body surfing, stood up on sandbar',
       'Surfing / Swimming', 'Body Boarding', 'Wade fishing',
       'Swimming breast stoke', 'Dived naked into the water on a bet',
       'Swimming with mask & snorkel', 'Playing / standing',
       'Abalone diving using Hookah (near calving whales)',
       'Abalone diving using Hookah (resting on the surface)',
       'Scuba diving (ascending using scooter)',
       'Commercial diver (submerged or treading water)',
       'Surfing, paddling seawards', 'Jumped off rocks into white water',
       'Hookah diving', 'Riding floatation device',
       'Free diving for abalone (ascending)',
       'Paddling on surfboard or body board',
       'Scuba diving at seal colony', 'Paddling on surfboard',
       'Free diving & spearfishing (ascending)',
       'Standing in waist-deep water, helping his father tend a gill net containing dead fish',
       'Lying on surfboard', 'Spearfishing / free diving',
       'Scuba diving (submerged)', 'Hookah diving for sea urchins',
       'Finning the shark that bit him', 'Swimming behind sailboat',
       'Sitting on surfboard', 'Surfing, collided with shark',
       'Free diving / spearfishing, from paddleboard & floating on the surface',
       "Fishing, stepped on hooked shark's head",
       'Hookah diving for abalone (descending)', 'Feeding fish',
       'Surfing with dolphins', 'Sittting in water with his child',
       'Free diving  & spearfishing (submerged)',
       'Hookah diving for abalone', 'Free diving for scallops',
       'Scuba Diving for lobster (at surface)',
       'Sailing on catamaran & fell into the water',
       'Surfing or body surfing', 'Skindiving',
       'Towing her sister on plastic ski board',
       'Swimming from the New Venture ',
       '14 m prawn trawler New Venture capsized  & sank in heavy seas Three people in the water',
       'Water-skiing', 'Free diving for abalone from Zodiac (submerged)',
       'Paddle Boarding', 'Standing / Wading',
       'Free diving for abalone (surfacing)',
       'Spearfishing / Scuba diving',
       'Hookah diving for abalone (submerged)',
       'Scuba diving & spearfishing', 'Floating on a small orange raft ',
       'Scuba diving for abalone',
       'Scuba diving for abalone (at surface)',
       'Swimming underwater from crayfish cage to a fishing bait',
       'Scuba diving (but on surface)', 'Free diving (but on surface)',
       'Scuba diving & feeding fish', 'Feeding mullet to sharks',
       'Spearfishing using Scuba', 'Standing on sandbar',
       'Pulling shark from the water',
       'Spearfishing, dived to pick up a float line',
       'Anti-sabotage night dive exercise alongside destroyer (Scuba diving)',
       'Free diving, carrying speargun', 'Spearfishing on Scuba',
       'Killing a shark', 'Clamming',
       'Free diving / spearfishing (resting on the surface)',
       'Free diving with seals', 'Surfing, but swimming to his board',
       'Spearfishing using scuba',
       'Attempting to swim across the Atlantic Ocean', 'Skin diving ',
       'Spearfishing / Scuba diving (at surface)',
       'Surf fishing, wading ', 'Spearfishing, pulled shark\x92s tail',
       'Surf fishing in waist-deep water', 'Fishing for albacore',
       'Rolled off raft',
       'Scuba diving, attempting to catch a captive shark',
       'Surfing, pushing board ashore',
       'Swimming with other crew near wharf',
       'Net fishing, picking catch from the net',
       'Walking in chest-deep water', 'Splashing ',
       'Checking fish traps, fell into the water',
       'Collecting aquarium specimens',
       'Fishing, when line became snagged on rock & he dived into water to free it ',
       'Holding shark on leader & dangling it above the water',
       'Fishing, tossing netted shark onboard',
       'Skindiving for abalone (but at surface)',
       'Wading, fishing for flounder', 'Standing in chest-deep water',
       'Trailing the field in a surf race',
       "Swimming at surface through school of feeding 2.5' to 5\x92 sharks",
       "Adrift, hanging onto cushion, after his 17' skiff ran out of gas & capsized 3 miles from shore",
       'Spearfishing (but on surface)', 'Working prawn net',
       'In deep water about 100 yards from his ship',
       'Surfing, but treading water', 'Surfing on air mattress',
       'Swimming, ducking for shells in water 0.9 m deep',
       'Competing in spearfishing championship & towing dead fish',
       'Swimming between  anchored  pearling luggers',
       'Swimming near pier', 'Swimming, attacked at  surf carnival',
       'Diving into water', 'Hunting lobsters in 2.4 m of water',
       'Pearl diving from lugger Whyalla', 'Fishing, setting nets',
       'Body surfing & treading water', 'Fell off surf ski',
       'Body surfing / treading water',
       'Free diving or wading back to shore',
       'Bathing in water 0.9 m deep', 'Lifesaving exhibition',
       'Underwater photography', 'Swimming after a tennis ball',
       'Dog paddling or standing', "Fishing from 32' boat",
       'Diving off jetty',
       'Diving from the lugger San, operated by the Protector of the Aborigines',
       'Refused permission to cross on the ferry, he was swimming across the river',
       'Swimming crawl stroke', 'Diving for trochus',
       'Swimming. Passer-by, Len Bedford, heard him shriek , saw shark leap from the water & swimmer disappeared',
       'Fell overboard, hanging onto lifebuoy', 'Splashing',
       'Swimming in waist-deep water ', 'Swimming in hip-deep water',
       'Swimming on sandbar adjacent to channel',
       'Diving off pier & treading water', 'Standing in knee-deep water',
       'Bathing', 'Swimming with dog near canning factory',
       'Floating on his back', 'Bathing in waist-deep water',
       'Had just dived into water & was swimming',
       "Bathing in 3' to 4' of water", 'Bathing in knee-deep water'],
      dtype=object)

In [74]:
#No ha habido ataques en Australia mientras practicaban Paddling
attacks_pad_AUSTRALIA=attacks_USA_AUSTRALIA[(attacks_USA_AUSTRALIA['country']== 'AUSTRALIA')&(attacks_USA_AUSTRALIA['activity']== 'Paddling')]
attacks_pad_AUSTRALIA

Empty DataFrame
Columns: [case_number, unnamed:_0, year, type, country, area, location, activity, name, sex_, age, time, species_, href]
Index: []

- 4.3 ¿Cuántos ataques se han producido en Australia antes del 2000?

In [75]:
#Filtramos los datos del dataframe para mostrar solo aquellos del pais "AUSTRALIA", antes del año 2000 (no incluido).
attacks_bf2000_AUS=attacks_USA_AUSTRALIA[(attacks_USA_AUSTRALIA['country']== 'AUSTRALIA')&(attacks_USA_AUSTRALIA['year']<2000)]
attacks_bf2000_AUS

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
2116,1999.05.29,2123,1999.0,Unprovoked,AUSTRALIA,South Australia,"Hardwicke Bay, Yorke Peninsula",Windsurfing,Tony Donoghue,M,22,14h30,Thought to involve a white shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2129,1999.02.23,2136,1999.0,Unprovoked,AUSTRALIA,New South Wales,Scotts Head,Surfing,male,M,35,Evening,Bronze whaler or tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2174,1998.06.28.a,2181,1998.0,Unprovoked,AUSTRALIA,South Australia,South Neptune Island,Free diving for abalone,Doug Chesser,M,26,14h00,Thought to involve a 5.5 m white shark named Kong,http://sharkattackfile.net/spreadsheets/pdf_di...
2194,1998.01.28.R,2201,1998.0,Invalid,AUSTRALIA,New South Wales,Whale Beach,Spearfishing,male,M,31,20h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
2207,1997.11.09,2214,1997.0,Unprovoked,AUSTRALIA,Western Australia,Albany,Scuba diving (submerged riding a scooter),Kevin Hulkes,M,42,Morning,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5359,1912.01.26,5375,1912.0,Unprovoked,AUSTRALIA,New South Wales,"Fig Tree Bridge, Lane Cove River, near Sydney",Swimming,James Edward Morgan,M,21,15h00,"2.8 m [9'3""] whaler shark captured 3 days late...",http://sharkattackfile.net/spreadsheets/pdf_di...
5481,1905.03.26,5498,1905.0,Unprovoked,AUSTRALIA,New South Wales,Lismore,Bathing,Richard Owen,M,40,Morning,5' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...

- 4.4 ¿Y después del 2000?

In [76]:
#Filtramos los datos del dataframe para mostrar solo aquellos del pais "AUSTRALIA", a partir del año 2000 (no incluido).
attacks_af2000_AUS=attacks_USA_AUSTRALIA[(attacks_USA_AUSTRALIA['country']== 'AUSTRALIA')&(attacks_USA_AUSTRALIA['year']>2000)]
attacks_af2000_AUS

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
21,2018.04.25.a,21,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
36,2018.03.14,36,2018.0,Unprovoked,AUSTRALIA,Western Australia,Waterman's Bay,Wading,Luke Guy & Finn Bald,M,10,17h35,Wobbegong shark,http://sharkattackfile.net/spreadsheets/pdf_di...
37,2018.03.09.b,37,2018.0,Unprovoked,AUSTRALIA,Victoria,Lorne,Swimming,Rob Crossland,M,69,15h30,3.5 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
38,2018.03.09.a,38,2018.0,Unprovoked,AUSTRALIA,Victoria,Winkipop,Surfing,Lachie Brown,M,18,07h30,1.8 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,2002.02.07,1883,2002.0,Boating,AUSTRALIA,New South Wales,Paramatta River (near Sydney),Kayaking,Paul McNamara,M,35,19h15,C. leucas tooth fragment recovered from kayak,http://sharkattackfile.net/spreadsheets/pdf_di...
1877,2002.01.30.b,1884,2002.0,Unprovoked,AUSTRALIA,New South Wales,Just north of Fingal Spit,Surfing,Andrew Cribb,M,20,20h45 (Sunset),"Tiger shark, 3 m [10']",http://sharkattackfile.net/spreadsheets/pdf_di...
1888,2001.10.02,1895,2001.0,Unprovoked,AUSTRALIA,Queensland,200 miles offshore,Snorkeling,Katherine Jones,F,20,13h00,Bronze whaler shark?,http://sharkattackfile.net/spreadsheets/pdf_di...
1961,2001.04.02.a,1968,2001.0,Unprovoked,AUSTRALIA,New South Wales,Nambucca River Entrance,Surfing,Richard Ellis,M,40,10h00,Bronze whaler shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1969,2001.02.04,1976,2001.0,Unprovoked,AUSTRALIA,New South Wales,Broome Head,Surfing,Mark Butler,M,40,16h15,"Bronze whaler shark, 2.5 m [8.25'] k",http://sharkattackfile.net/spreadsheets/pdf_di...

5. Extraed unicamente los ataques a mujeres.

In [78]:
#Filtramos los datos del dataframe por sexo femenino.
attacks_F= attacks_lec3[attacks_lec3['sex_']== 'F']
attacks_F

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
40,2018.02.23,40,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
53,2017.12.31,53,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
71,2017.10.22,71,2017.0,Unprovoked,AUSTRALIA,South Australia,Normanville,Kayaking / Fishing,Sarah Williams,F,15,Afternoon,"White shark, 4.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
75,2017.10.05,75,2017.0,Unprovoked,USA,Hawaii,"Kamaole Beach Park, Maui",Snorkeling,female,F,40,12h30,8' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4151,1958.04.05,4163,1958.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Uvongo,Paddling in knee-deep water,Fay Jones Bester,F,28,11h10,3 m [10'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4170,1957.12.30,4182,1957.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Margate,Standing,Julia Painting,F,14,12h40,1.8 m [6'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4678,1942.12.26,4690,1942.0,Unprovoked,AUSTRALIA,New South Wales,"Bantry Bay, near Ironstone Point, Middle Harbo...",Dog paddling or standing,Denise Rosemary Burch,F,15,10h50,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4706,1942.01.04,4718,1942.0,Unprovoked,AUSTRALIA,New South Wales,"Egg Rock, Middle Harbor, Sydney",Swimming,Zita Steadman,F,28,15h00,"Bull shark, 4 m [13']",http://sharkattackfile.net/spreadsheets/pdf_di...
4913,1934.12.31.b,4925,1934.0,Unprovoked,AUSTRALIA,New South Wales,Georges River at Kentucky,Splashing,Beryl Morrin,F,13,20h15,"Tiger shark, 1.5 m [5']",http://sharkattackfile.net/spreadsheets/pdf_di...

6. ¿Cuántas mujeres fueron atacadas en España?

In [79]:
#Filtramos los datos del dataframe por sexo femenino y ocurridos en el pais "SPAIN".
attacks_F_SPAIN= attacks_lec3[(attacks_lec3['sex_']== 'F')&(attacks_lec3['country']=='SPAIN')]
attacks_F_SPAIN

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
98,2017.08.26.b,98,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...

7. Extraed los ataques que se hayan producido en el año 2000, 1997 y 2006. Utilizad el método isin() para resolver este ejercicio.

In [80]:
#Mostramos los ataque sproducidos en los años 1997, 2000 y 2006, para ello utilizamos el metodo ".isin()".
attacks_years=attacks_lec3[attacks_lec3['year'].isin([2000,1997,2006])]
attacks_years

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
1407,2006.12.18,1412,2006.0,Unprovoked,AUSTRALIA,Victoria,"Winki Pop, Bells Beach",Surfing,Peter Galvin,M,25,20h00,2.5 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1408,2006.12.11,1413,2006.0,Unprovoked,NEW ZEALAND,North Island,"Raglan, Manu Bay",Surfing,Elliot Paerata-Reid,M,10,11h00,2 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1409,2006.12.10,1414,2006.0,Unprovoked,USA,California,"Dillon Beach, Marin County",Surfing,Royce Fraley,M,43,11h50,"White shark, 12' to 15'",http://sharkattackfile.net/spreadsheets/pdf_di...
1410,2006.12.06,1415,2006.0,Provoked,SOUTH AFRICA,KwaZulu-Natal,Cape Vidal,Fishing,Peter Willoughby,M,25,"""Evening""","Raggedtooth shark, 150-kg",http://sharkattackfile.net/spreadsheets/pdf_di...
1411,2006.12.02,1416,2006.0,Unprovoked,AUSTRALIA,Western Australia,Wharton Beach,Body boarding,Zac Golebiowski,M,15,07h30,"White shark, 5m",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2246,1997.05.31.b,2253,1997.0,Unprovoked,USA,Florida,"Flagler Beach, Flagler County",Surfing,Robert Fuller,M,34,11h00,Possibly a sand shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2247,1997.05.31.a,2254,1997.0,Unprovoked,USA,Florida,"Flagler Beach, Flagler County",Surfing,Johnny Bowden,M,12,11h00,Possibly a sand shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2252,1997.02.28.a,2259,1997.0,Unprovoked,AUSTRALIA,Queensland,Whitsunday Passage,Scuba diving,Gerald Rauch,M,30,Midday,"Tiger shark, 2m to 3m",http://sharkattackfile.net/spreadsheets/pdf_di...
2256,1997.01.25,2263,1997.0,Unprovoked,AUSTRALIA,Queensland,"Whitehaven Beach, Whitsundays Island",Snorkeling,Derek Burrows,M,27,11h00 / 11h30,1.8 m to 2.1 m [6' to 7'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2257,1997.01.20,2264,1997.0,Unprovoked,AUSTRALIA,Western Australia,Geraldton,Windsurfing,Werner Schonhofer,M,41,18h00,"Tiger shark, 4.5 m [14'9""]",http://sharkattackfile.net/spreadsheets/pdf_di...

8. Si extraemos los valores únicos de la columna species nos podemos dar cuenta que está un poco sucia y extraer informacion útil de la misma se puede convertir 
en algo difícil. En este ejercicio tendréis que extraer los ataques que han ocurrido por tiburón blanco (lo encontraremos en la columna species como algo que 
contenga white o White). Usad el método str.contains() para resolver este ejercicio.

In [81]:
#Empleando el metodo ".std.contains()" mostramos las filas que contienen en la columna especificada el patron regex que le introducimos.
attacks_species=attacks_lec3[attacks_lec3['species_'].str.contains('\w+hite',case =False, regex=True)]
attacks_species

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
24,2018.04.22,24,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,33,09h40,"White shark, 2.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
34,2018.04.03,34,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,Ross Spowart,M,19,15h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
40,2018.02.23,40,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
60,2017.11.24,60,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5212,1922.05.06,5225,1922.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Simons Town, False Bay",Swimming,Edward G. Pells,M,18,A.M.,"White shark, 12', identity confirmed by tooth ...",http://sharkattackfile.net/spreadsheets/pdf_di...
5216,1922.03.02,5229,1922.0,Unprovoked,AUSTRALIA,New South Wales,Coogee,Bathing in knee-deep water,Mervyn Gannon,M,21,11h00,"White shark, 2.4 m [8']",http://sharkattackfile.net/spreadsheets/pdf_di...
5218,1922.02.04,5231,1922.0,Unprovoked,AUSTRALIA,New South Wales,Coogee,Swimming,Milton Coughlan,M,18,15h30,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5297,1916.07.01,5311,1916.0,Unprovoked,USA,New Jersey,"Beach Haven, Ocean County",Swimming,Charles E. Vansant,M,24,17h00,Thought to involve a 2.6 m [8.5'] white shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...

9. Extraed ahora los ataques por tiburón blanco o tigre. Utilizad el método str.contains() para resolver este ejercicio.

In [88]:
attacks_species=attacks_lec3[(attacks_lec3['species_'].str.contains('\w+hite',case =False, regex=True))|(attacks_lec3['species_'].str.contains('[T|t]iger',case =False, regex=True))]
attacks_species

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
18,2018.04.28.b,18,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,male,M,30,10h40,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
23,2018.04.23,23,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,Ahmed Rasheed,M,32,21h50,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
24,2018.04.22,24,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,33,09h40,"White shark, 2.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5212,1922.05.06,5225,1922.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Simons Town, False Bay",Swimming,Edward G. Pells,M,18,A.M.,"White shark, 12', identity confirmed by tooth ...",http://sharkattackfile.net/spreadsheets/pdf_di...
5216,1922.03.02,5229,1922.0,Unprovoked,AUSTRALIA,New South Wales,Coogee,Bathing in knee-deep water,Mervyn Gannon,M,21,11h00,"White shark, 2.4 m [8']",http://sharkattackfile.net/spreadsheets/pdf_di...
5218,1922.02.04,5231,1922.0,Unprovoked,AUSTRALIA,New South Wales,Coogee,Swimming,Milton Coughlan,M,18,15h30,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5297,1916.07.01,5311,1916.0,Unprovoked,USA,New Jersey,"Beach Haven, Ocean County",Swimming,Charles E. Vansant,M,24,17h00,Thought to involve a 2.6 m [8.5'] white shark,http://sharkattackfile.net/spreadsheets/pdf_di...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...

10. Utilizando la columna de year cread una nueva columna llamada siglo que tiene siglo-XX o siglo-XXI. Donde el año sea menor que 2000 pondremos siglo-XX y el resto de los años siglo-XXI.

In [89]:
#Utilizamos el metodo de numpy 'np.where()' mediante el cual nos permite reemplazar los elementos que cumplan la condidicion especificada por los datos que le indicamos.
attacks_lec3['siglo']=np.where(attacks_lec3['year']<2000, 'siglo-XX','siglo-XXI')
attacks_lec3

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href,siglo
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
13,2018.05.13.a,13,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XX
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XX
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XX
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XX
5905,1868.05.13,5922,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XX

11. Guardad como un archivo csv nuevo. Lo usaremos en el pair programming de mañana.

In [90]:
#Efecutamos el guardado del archivo en un csv nuevo asociado a la lecccion 4 con los ejercicios realizados en dicha leccion.
attacks_lec3.to_csv('Data_lecc4_pandas/attacks_lec4.csv')

Happy coding 🦈